package ar.edu.huergo.fastbid.entity.historial;

public enum HistorialTipoEvento {
    CREACION_SUBASTA,
    SUBASTA_GANADA,
    PUJA_NUEVA,
    ESTADO_CAMBIADO,
    COMPRA_INMEDIATA,
    PAGO_APROBADO,
    PAGO_FALLIDO,
    ENVIO_ACTUALIZADO,
    SUBASTA_CANCELADA,
    SUBASTA_FINALIZADA,
    PRODUCTO_ASOCIADO,
    PRODUCTO_DESASOCIADO,
    PRODUCTO_CREADO,
    PRODUCTO_ELIMINADO,
    CATEGORIA_CREADA,
    CATEGORIA_ELIMINADA
}
